name: Build and Test Go App

on:
  workflow_call:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' 

      - name: Download Go modules
        run: go mod download

      - name: Build app
        run: go build ./microservice/cmd/main.go

      - name: Run unit tests
        run: go test ./microservice/... -v
